server:
    port: 8002
mybatis:
    type-aliases-package: com.jhy.springcloud.pojo
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml


spring:
    application:
        name: springcloud-provider-user
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url:
        username:
        password: