server:
  port: 9002

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    #        register-with-eureka: false
    #        fetch-registry: false
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: zuul9002
    prefer-ip-address: true

info:
  app.name: jht.springcloud
  company.name: tencent

zuul:
  routes:
    myuser.serviceId: springcloud-provider-user
    myuser.path: /myuser/**
  ignored-services: springcloud-provider-user