server:
    port: 8003
mybatis:
    type-aliases-package: com.jhy.springcloud.pojo
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml


spring:
    application:
        name: springcloud-provider-user
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://81.70.240.178:3306/spring2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: zhaoqi

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
    instance:
        instance-id: spring-provider-user8003

info:
    app.name: jhy
    company.name: tencent