server:
  port: 7003

eureka:
  instance:
    hostname: eureka3
  client:
    register-with-eureka: false   #是否需要注册自己
    fetch-registry: false  #false 自己为注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/erueka
      defaultZone: http://eureka2:7002/eureka/,http://eureka1:7001/eureka/