server:
  port: 80

eureka:
  client:
    register-with-eureka: false   #是否需要注册自己
    service-url:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/erueka
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
    fetch-registry: true
